name: pointstowood
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - pip
  
  # PyTorch ecosystem (GPU support)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8  # or 12.1 depending on your CUDA version
  
  # PyTorch Geometric
  - pyg>=2.3.0
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  
  # Scientific computing
  - numpy>=1.21.0
  - pandas>=1.5.0
  - scikit-learn>=1.1.0
  
  # Visualization and utilities
  - matplotlib>=3.5.0
  - tqdm>=4.64.0
  
  # Point cloud processing
  - laspy>=2.0.0
  
  # Development tools (optional)
  - jupyter
  - ipython
  - pytest
  
  # Install via pip (packages not available via conda)
  - pip:
    - pykdtree>=1.3.0
    - numba>=0.56.0